repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    language_version: python3.6
    files: \.py$
    additional_dependencies: [
      "git+https://github.com/ambv/black.git@2ae5ce1e6ee036b48db48342512f6d3726f77682",
    ]
    args: ["-l79"]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    files: \.py$
    additional_dependencies: ["flake8==3.7.6"]
