repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    language_version: python3.6
    files: \.py$
    additional_dependencies: [
      "git+https://github.com/ambv/black.git@2ae5ce1e6ee036b48db48342512f6d3726f77682",
    ]
    args: ["-l79"]
- repo: https://github.com/Landmaj/py-commit-hooks.git
  rev: v1.2.0
  hooks:
  - id: flake8

